[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Reporting-Endpoints = '''{
      "group":"default",
      "max_age":31536000,
      "endpoints":[
        {
          "url":"https://nordicgamelab.report-uri.com/a/d/g"
        }
      ],
      "include_subdomains":true
      }'''
    Content-Security-Policy = "default-src * 'self' data: 'unsafe-inline' 'unsafe-eval'; frame-ancestors https://*.nordicgamelab.org https://*.instructure.com; report-uri https://nordicgamelab.report-uri.com/a/d/g; report-to default;"

