[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Reporting-Endpoints = '''{
      "group":"default",
      "max_age":31536000,
      "endpoints":[
        {
          "url":"https://nordicgamelab.report-uri.com/a/d/g"
        }
      ],
      "include_subdomains":true
      }'''
    Content-Security-Policy = "default-src https://fonts.gstatic.com 'self' data: 'unsafe-inline' 'unsafe-eval' https://*.nordicgamelab.org https://www.canva.com https://maxcdn.bootstrapcdn.com code.tidio.co fw-cdn.com js.hs-scripts.com https://js-agent.newrelic.com https://app.posthog.com https://*.sentry-cdn.com https://js.hscollectedforms.net https://js.hs-analytics.net https://js.hs-banner.com https://widget.freshworks.com https://www.clarity.ms static.nordicgamelab.org tag.clearbitscripts.com https://www.google.com https://www.googletagmanager.com https://x.clearbitjs.com https://js.hs-scripts.com; script-src 'self' data: 'unsafe-inline' 'unsafe-eval' https://*.nordicgamelab.org https://*google* https://maxcdn.bootstrapcdn.com https://js.hs-scripts.com https://js.hscollectedforms.net https://code.tidio.co https://js.sentry-cdn.com https://app.posthog.com https://tag.clearbitscripts.com; frame-src www.canva.com; img-src 'self' betteruptime.com data: https://cdn.dribbble.com '*'; script-src-elem 'self' 'unsafe-inline' code.tidio.co fw-cdn.com js.hs-scripts.com https://js-agent.newrelic.com https://app.posthog.com https://*.sentry-cdn.com https://js.hscollectedforms.net https://js.hs-analytics.net https://js.hs-banner.com https://widget.freshworks.com https://www.clarity.ms static.nordicgamelab.org tag.clearbitscripts.com https://www.google.com https://www.googletagmanager.com https://x.clearbitjs.com https://js.hs-scripts.com; style-src-attr 'unsafe-inline'; style-src-elem 'self' https://fonts.googleapis.com maxcdn.bootstrapcdn.com; frame-ancestors https://*.nordicgamelab.org; report-uri https://nordicgamelab.report-uri.com/a/d/g; report-to default"

